name: Sync upstream Spark job

on:
  pull_request:
    paths:
    - '.github/workflows/spark-sync.yaml'
    # Runs at every pull requests submitted in master branch 
    branches: [ master ]
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '0 */8 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache kunpengcompute src repos
      uses: actions/cache@v2
      with:
        path: /home/runner/work/Kunpeng/Kunpeng/spark-cache
        key: ${{ runner.os }}-spark-cache
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@v1.0
      with:
        src: github/apache
        dst: github/kunpengcompute
        dst_key: ${{ secrets.HUB_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITHUB_TOKEN }}
        account_type: org
        timeout: 600
        debug: true
        force_update: true
        static_list: "spark,spark-website"
        cache_path: /github/workspace/spark-cache
